version: '3.4'

services: 

  frontend:
    image: storeimage
    build:
      context: .
      dockerfile: DockerfileStore
    environment: 
      - ProductEndpoint=http://backend:8080
      - ImagePrefix=https://animated-succotash-qx444w77763v4g-5200.app.github.dev/
    ports:
      - "5902:8080"
    depends_on: 
      - backend
  backend:
    image: productservice
    build: 
      context: .
      dockerfile: DockerfileProducts
    ports: 
      - "5200:8080"